output_dir: data/

apis: [YahooBursaFetcher]
instruments: ["SPY", "AAPL", "GLD", "EURUSD=X", "EEM"]

# fetching parameters
to_fetch: True # False - load previously saved data
fetch_date: '2023-10-17'

historical_params:
  period: "1y"
  interval: "1d"

# preprocessing parameters
to_preprocess: True # False - load previously saved data